export default {
  ADD_TO_CART: 'ADD_TO_CART',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  UNLOG: 'UNLOG',
  RELOGIN: 'RELOGIN',
  LOGGING: 'LOGGING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SIGNING: 'SIGNING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  ADD_TO_RECORDS: 'ADD_TO_RECORDS',
};
